# Database
db:
  rootPassword: rootpassword
  database: travelo
  user: travelo_user
  password: travelo_pass
  storage: 1Gi

# Backend
backend:
  image: docker.io/samoyuom/travelo-backend
  tag: "1.0"
  replicas: 2
  port: 8080

# Frontend
frontend:
  image: docker.io/samoyuom/travelo-frontend
  tag: "1.0"
  replicas: 2
  port: 80

# Ingress
ingress:
  host: travelo-helm.local