services:
  registry:
    image: registry:2
    container_name: private-registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry-data:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "Travelo Private Registry"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      PULL_URL: "127.0.0.1:5000"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      SHOW_CATALOG_NB_TAGS: "true"
    depends_on:
      - registry

volumes:
  registry-data: