apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: travelo
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-database: travelo
  mysql-user: travelo_user
  mysql-password: travelo_pass