apiVersion: v1
kind: ConfigMap
metadata:
  name: travelo-config
  namespace: travelo-helm
data:
  DB_HOST: travelo-db
  DB_PORT: "3306"
  DB_NAME: {{ .Values.db.database }}
  SPRING_DATASOURCE_URL: jdbc:mysql://travelo-db:3306/{{ .Values.db.database }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.db.user }}