apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelo-frontend
  namespace: travelo-helm
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: travelo-frontend
  template:
    metadata:
      labels:
        app: travelo-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10