apiVersion: v1
kind: ServiceAccount
metadata:
  name: travelo-sa
  namespace: travelo-helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travelo-role
  namespace: travelo-helm
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travelo-rolebinding
  namespace: travelo-helm
subjects:
  - kind: ServiceAccount
    name: travelo-sa
    namespace: travelo-helm
roleRef:
  kind: Role
  name: travelo-role
  apiGroup: rbac.authorization.k8s.io