apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: travelo-helm
type: Opaque
stringData:
  mysql-root-password: {{ .Values.db.rootPassword }}
  mysql-database: {{ .Values.db.database }}
  mysql-user: {{ .Values.db.user }}
  mysql-password: {{ .Values.db.password }}